Sitz:(20a)Peine,Gerhardstr.10.
Fernruf:Peine2641,2609und
2741,
Grossilsede541.
Fernschreiber:
023965/66huettenwpeine.
Vorstand:.
DiedrichDännemark,Peine;
HelmuthHeintzmann,Herne;
PaulMöllenberg,Neu-Ölsburg;
Dr.KurtRasch,Peine.
Aufsichtsrat:
JuliusFromme,Peine,Vors.;
HermannBeermann,Hannover,1.stellv.
Vors.;
KarlSchirner,Freiburg(Breisgau),
2.stellv.Vors.;
Dr.KurtBlanke,Celle;
HeinrichFreiherrvonBerenberg-
Gossler,Hamburg;
Dr.WolfgangBode,Peine;
ErnstBöhme,Braunschweig;
OttoBrenner,Frankfurt(Main);
Dr.HansFiehn,Hannover;
BrunoHerrmann,Peine;
Dr.h.c.ErichLotz,Braunschweig-
Querum;
OttoMöhle,Langenhagen;
Dr.KarlRöhrs,Bonn;
FriedrichSchiwon,Herne;
JohannSmentek,Dürnten.
Gründung:1858.
Tätigkeitsgebiet:
Erzeugungvon:Erze,Kohle,Strom,
Gas,Benzol,Ammoniak,Teer,Schwefel,
Roheisen,Rohstahl,Schlacken,Thomas-
mehl,Halbzeug,Oberbaumaterial,
Formstahl,Stabstahl,Spundwände,
Breitflanschträger,Universaleisen.
Haupterzeugnisse:
Form-undStabstahl.
Spezialitäten:
Breitflanschträger("PeinerTräger"),
Spundbohlen,Spantenprofilefürden
Schiffbau.
OrganisatorischbietetdieGesellschaft
nunmehrfolgendesBild:
IlsederHüttealsHoldinggesellschaftmit
denTochtergesellschaften
a)HüttenwerkeIlsede-PeineAGmitihren
AbteilungenErzbergbau,Hochofenwerk,
Stahl-undWalzwerkunddenUnterge-
sellschaftenKalkwerkMarienhagenGmbH
undSüntelschotterwerkeDr.Schmidt&Co.
K.-G.,Pötzen;
b)SteinkohlenbergwerkFriedrichder
GrosseAGmitdenKohlenzecheninHerne
undMindenundderUntergesellschaft
BergarbeiterwohnungsgesellschaftmbH
"Glückauf",Herne.
c)Industrie-undHandels-AG,Peinemit
7Tochtergesellschaften;
d)GewerkschaftKonrad,die1954vonder
IlsederHütteundderAGfürBerg-und
Hüttenbetriebe,Berlin,alsGewerken
miteinerBeteiligungvonje50%gegrün-
detwurde.
Besitz-undBetriebsbeschrei-
bungderTochtergesellschaften:
1.HüttenwerkeIlsede-PeineAG
Erzbergwerke(Brauneisenerze).Diever-
schiedenenErzvorkommenbeiBüiten,
LengedeundimSalzgitterschenHöhenzug
machendasHochofenwerkunabhängigvon
jedemBezugfremdenErzes.DieRoherze
werden,soweitnötig,ineigenerErzwä-
schegewaschenundaufeigenenBahnen
demHüttenwerkzugeführt.
Hüttenwerk.Hochofenwerk,Kokereimit
Nebengewinnungsanlage,Erzsieberei,
Erzagglomerieranlage;eineeigeneGicht-
gaskraftanlageversorgtBergbau,Hütte
undWalzwerkundzahlreicheOrtschaften
mitStrom,undderÜberschussanKoke-
reigaswirdalsFerngasandasPeiner
Walzwerk,dieStadtHiidesheimunddie
LandesgasversorgungSüd-Niedersachsen
AGabgegeben.EigeneHafenanlagen.
Walzwerk.Anlagen:Thomas-undSie-
mens-Martin-Stahlwerk,Walzenstrassen,
Thomasschlackenmühle.
Eisenbahnen.SiedieneninersterLinie
derVerbindungderWerksanlagenunter
sich,undzwarvondenErzgrubenzum
Hochofenwerk,vondiesemzumWalzwerk
undvondiesemzumAnschlussandie
Bundesbahn.EinigeStreckendienenauch
demöffentlichenVerkehr.
SonstigerBesitz:
2131werkseigenesowie722werksge-
bundeneWohnungen.
Beteiligung:
93,75desStammkapitalsderKalk-
werkMarienhagenGmbH
40%desStammkapitalsderSüntel-
schotterwerkeDr.Schmidt&Co.,K.-G.,
Pötzen.
2.SteinkohlenbergwerkFried-
richderGrosseAG
GerechtsameinHerne:8952124qm.
AufGrundeinesPachtvertragesmitden
Klöckner-WerkenüberdasBaufeld
Victor-Ickern2beträgtdasinsgesamt
zurVerfügungstehendeBaufeldrund
18Mioqm.
DieBetriebsanlageninHerneumfassen
dieSchachtanlagen1/2,3/4und5mit
denzugehörigenEinrichtungen.Siesind
imInteresseeinermöglichstwirtschaft-
lichenBetriebsführungzueinerAnlage
zusammengefasst.
GerechtsameinMinden:10Längenfelder
mit9562mstreichenderLängeund4
Geviertfeldermit5350000qm.Dane-
benbestehteinPachtvertragmitder
Preussag.
Schachtanlagen:NoithornundRöcke.
KokereiinHerne:53Öfen;Kapazität
1150ta/to.
SonstigerBesitz:
1721werkseigeneWohnungen.
Beteiligung:
75%desStammkapitalsderBergarbeiter-
wohnungsgesellschaftmbH"Glückauf".
MitbeidenTochtergesellschaften,die
100%imBesitzderGesellschaftsind,
bestehenOrganschafts-undGewinn-und
Verlustübernahmverträge.
3.Industrie-undHandels-AG
Peine
DieGesellschaft,diemiteinemGrund-
kapitalvonDM10224000.-ausge-
stattetist,isteinereineObergesellschaft.
IhreTochtergesellschaftensind:
dieNorddeutscheSchrauben-undMuttern-
werkeAG,Peine,miteinemGrund-
kapitalvonDM2,88Mio,dassichzu
92,6%inHändenderIHAGundzu7,05%
inHändenderIlsederHüttebefindet;
dasProduktionsprogrammderGesell-
schaftumfaßtSchrauben,Schalungsträger
undanderesBaugerätsowieKräne;
diePeine-IlsederHandelsgesellschaft
mbH,derenStammkapitalvonDM4Mio
zu100%imIHAG-Besitzistunddieim
GroßhandelmitEisen-undStahlerzeugnis-
sensowieDüngemittelntätigist;
diePeinerStahlbauundEisenhandelGmbH,
Berli-n,miteinemStammkapitalvon
DM1,2Mio,dasvollständiginHänden
derIHAG(12,5%)undderPeine-Ilseder
Handelsgesellschaft(87,5%)ist;
dieHermannRüterOHG,Hannover-
Langenhagen,derenKapitalvonDM2,04
Miozu88,24%derIHAGundzu11,76%
derPeine-IlsederHandelsgesellschaft
gehörtunddieebensowiedievorherge-
nannteGesellschaftdieHerstellungvon
Brücken-undStahlhochbautensowieden
GroßhandelmitEisen-undStahlerzeugnis-
senbetreibt;
dieHubertJosefHeineEisenhandels-KG,
Dortmund,vonderenKapital(DM423000.-)
dieIHAGeinenKommanditanteilinHöhe
vonDM300000.-besitzt;
dieIlsederBank,Sandow&&Co.,Peine,
diezu100%imIHAG-Besitzistsowie
dieBraunschweigerHüttenwerkGmbH,
Braunschweig,anderenStammkapital
inHöhevonDM1,8MiodieIHAGeinen
Anteilvon26,33%hat;dieseGesellschaft
istmitderHerstellungvonLagermetall
undGleit-undWalzlagernbeschäftigt.
4.GewerkschaftKonrad,Salz-
gitter-Drütte
DieGesellschaft,derenKuxenkapital
vonDM136000.-(Stand30.9.1955)zu
je50%derIlsederHütteundderAGfür
Berg-undHüttenbetriebe,Berlin,gehört,
befindetsichnochimAufbau.
Geschäftsjahr:Kalenderjahr.
Stimmrechtd.Aktieni.d.H.-V.:
Jenom.DM100.-=1Stimme.
Zahlstellen:
Gesellschaftskasse;
IlsederBank,Sandow&Co.;
Commerz-undDiasconto-BankAG;
sämtlichPeine;
NorddeutscheBankAG;
Commerz-undDisconto-BankAG;
HamburgerKreditbankAG;
sämtlichBraunschweig,Bremen,Ham-
burgundHannover;
BerlinerDiscontoBankAG;
BankfürHandelundIndustrieAG;
BerlinerCommerzbankAG;
BerlinerHandels-Gesellschaft;
sämtlichBerlin;
BraunschweigischeStaatsbank,Braun-
schweig;
NorddeutscheKreditbankAG,Bremen;-
NorddeutscheBankAG;
HamburgerKreditbankAG;beideCelle;
DeutscheBankAGWest;
Rhein-RuhrBankAG;
Commerzbank-BankvereinAG;
sämtlichDüsseldorf;
SüddeutscheBankAG;
Rhein-MainBankAG;
Commerz-undCredit-BankAG;
sämtlichFrankfurt(Main)undMünchen;
BerlinerHandels-Gesellschaft;
FrankfurterBank;
MetallgesellschaftAG;
sämtlichFrankfurt(Main);
Berenberg,Gossler&Co.,Hamburg;
BayerischeVereinsbank,München.
Grundkapital:DM112320000.-
UmstellungIt.H.-V.v.26.11.1952im
Verh.1:1,75undsogleichaufDM
102240000.-herabgesetzt.
Lt.H.-V.vom8.7.1955Erhöhungum
DM10080000.-aufDM112320000.-.
Börsennotiz:
HannoverundimFreiverkehrBerlin
undHamburg.
Ordnungsnr.d.Aktien:620200.
Stückelung:
99856St.-Akt.zujeDM1000.-
(Nr.1-99856)
124640St.-Akt.zujeDM100.-
(Nr.300001-424640)
SämtlicheStammaktiensindlieferbar.
Grossaktionär:
VereinigteIndustrie-Unternehmungen
AG,Berlin/Bonn(25,1%).
Anleihe:
6%Amerika-Anleihevon1928/48
Emissionsbetrag:$10000000.-.
47/8%SchweizerFrankenAnleihevon
derHohenBehördederMontan-Union
Emissionsbetrag:sfrs.8000000.-.
Aktienkurse:
ultimo194819,5%
194973%
1950713,5%
„1951179%
1952145%
"1953140%
u1954179,25%
"1955184%
10.Okt.1956185,5%+)
+)KursfürDM-Nennwert.
DividendenaufStammaktien:
1948/49:0%
1950:0%
1951:5%(Div.Sch.Nr.12)
1952:6%(Div.Sch.Nr.13)
1953:6%
1954:7%(Div.Sch.Nr.1)
1955:9%(Div.Sch.Nr.2)
ZurGeschäftslage:
GuterAbsatzallerimBereichderIlseder
Hüttegefördertenbzw.produziertenEr-
zeugnisse.
AusdenBilanzen
31.12.195431.12.1955
(in1000DM)
Anlagevermögen234352234570
Umlaufvermögen65602939
(darunter
Barmittel)5875
Eigenkapital206874206869
(davonA.-K.)102240102240
Fremdkapital2669621165
GewinnnachVortrag73429475
�
AusdenGewinn-undVerlust-
rechnungen
LöhneundGehälter568620
Abschreibungen863
Steuern566316519
Jahresertrag7711226342
Beteiligungserträge20-
HHedwigshütteKohlen-undKokswerkeAktiengesellschaft
